name: quaderno_flutter
description: QuadernoTorneo again, flutter way

publish_to: "none"

version: 3.1.7+17

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  adaptive_dialog: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  blinking_text: ^1.0.2
  cupertino_icons: ^1.0.5
  data_table_2: ^2.3.8
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  # flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  formz: ^0.6.1
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  hive: ^2.2.3
  hive_flutter: 1.1.0
  http: ^1.0.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  logging: ^1.1.0
  package_info_plus: ^5.0.1
  pull_to_refresh: 2.0.0
  rxdart: ^0.27.5
  supabase_auth_ui: ^0.2.1
  supabase_flutter: ^1.10.25
  transparent_image: ^2.0.0
  url_launcher: ^6.1.6
  user_repository:
    path: packages/user_repository
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_native_splash: ^2.2.13
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

flutter_native_splash:
  color: "#4CAF50"
  image: assets/images/players_with_logo.png
  web: false

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#548b2e"
  adaptive_icon_foreground: "assets/icons/quaderno_foreground.png"
  ios: true
  image_path: "assets/icons/quaderno.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/
